### ISSUE TITLE
Navbar messed up in Firefox

### ISSUE THREAD

**Issue by DavidDuwaer** [katharsis-project/katharsis.io#23]
Hey,

The layout of the website in Firefox appears like this:

![image](https://cloud.githubusercontent.com/assets/8791690/24528098/5d7e3028-15a5-11e7-8c5f-da2996cfec0b.png)

Notice the narrow black bar some distance blow the navbar. This bar stays at a fixed position from the navbar during scrolling. This happens both with Firefox in safe mode and in normal mode. In Chrome, the site looks fine.

**Comment by chb0github** [comment]
Thank you for the heads up.
